#!/usr/bin/env bash

package_file="$1"
test -z "$package_file" && package_file="../lair-frontend/package.json"

if ! test -f "$package_file"; then
  >&2 echo $package_file does not exist
fi

cp "$package_file" .
